### ISSUE TITLE
[TODO] Future implementations..?

### ISSUE THREAD

**Issue by juimdpp** [swsnu/swpp2020-team3#2]
!! Feel free to add more todos (preferably after meetings) !!

**Until end of sprint 2** (at the very very least):
- [x] Implement the recipe create page (expecting it will take a long time - lots of features)
- [x] Implement the recipe list page
- [x] Implement the sign up, log in, log out pages and features (authentication via Django) --> after HW4
- [x] Implement the recipe detail page

**Comment by juimdpp** [comment]
댓글 폭탄 처리 (댓글 1000개씩 생성 --> 댓글들 읽기 힘들어짐)

**Comment by juimdpp** [comment]
Add CAPTCHA API to test robots.
