### ISSUE TITLE
Createpage TODOlist

### ISSUE THREAD

**Issue by juimdpp** [swsnu/swpp2020-team3#38]
- [x] Make createpage accessible only for logged in user.
- [x] Retrieve ingredients from server
- [x] Resize images before previewing
- [ ] Make ingredient select component that displays icon. Or at least, Display icon upon selection, and display image of ingredient upon hover.
- [x] Fix bug where delete step doesn't delete the appropriate step.
- [x] Calculate normalized price in the backend, send it along with the ingredients dict.
- [x] Allow to input quantity of each ingredient. Calculate price.
- [x] Allow to input quantity by "types (g, units). Calculate price with normalized_price. (Right now, can only get by unit and calculate price of units, not exact grams.)
- [x] Fix bug where in the search bar, everything is selected after first select.
- [x] Fix: we can add infinitely many same ingredient which affects the totalprice
- [x] Add input for thumbnail
- [x] Make default of ingredient quantity 1
- [x] Add tags

// TODO: Now it renders with descriptionList. Instead make a single array where each element contains imageList,
//       descriptionList and imagePreviewList
// (?)TODO(?): abstract the add image part, but the problem is later, I will have to add a delete part...

**Comment by juimdpp** [comment]
Sprint 1: proposal
Sprint 2: specs
Sprint 3: 기본 큰 페이지들 구현 (create page, detail page, search/list page, main page, login, signup)
Sprint 4: change db to sql, my page, meal planner, machine learning api 사용
Sprint 5: 기말고사 시즌 때문에 이때는 구현 위주 보다는 테스팅 마무리하고, 디자인 마무리 하고, 포스터 제작, 버그 픽스, deploy.


# Implementation plan (tentative)

| Feature | Difficulties (1~5) | Times (days) | Sprint | Person | Challenge |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Sign up | 1 | 1| 2 | (김현수) | |
| Main page | 1 | 1 | 2 | 권지웅 | |
| Recipe list | 1 | 1 | 2 | 김훈 | |
| Create recipe | 1 |1| 2 | 김현수 | | 
| Comment | 2 | 4 | 3 | (김기덕) | |
| Recipe detail | 1 |1| 2|김기덕 | | 
| Retrieve ingredients | 3 | 5 | 3 | (김훈, 김현수) | |
| Seed the database | 1 | 2 | 3 | (김기덕, 권지웅) | |
| My page | 3 | 5 | 4 | (? ) | |
| Meal planner | 5 | 5 | (?) | |
| (ML) Recommend article | 4 | 6 | (all?) | The frontend and backend must work well |
| Board implementation | 3 | 7 | 3 | (권지웅, 김현수) | |
| Alert feature | 3 | 6 | 3 | (김기덕, 김훈) | |
| Testing | 2 | 10 | all | all | In particular, at the end of each sprint, we will assure min 90% coverage |
| Design | 2 | 10 | 4 | (권지웅 +alpha) | |
| Additional features | ? | 10 | 5 | - | adding login via social media,  |
