### ISSUE TITLE
[Sprint 5] TODO

### ISSUE THREAD

**Issue by juimdpp** [swsnu/swpp2020-team3#80]
일정:
(일) 11/29 : Sprint 5 시작
(목) 12/10 : Demo session (deploy 해야함)
(토) 12/12 : Sprint 5 끝 (리포트 제출)
(목) 12/17 : 포스터 세션 (포스터, 데모, 구현 완료)
(금) 12/18 : Final report 제출

- [ ]  ❗️**전인원 12/5 11:00까지** ❗️디비 채우기 (각각 50개의 recipe 만들기) 
```
\copy [Table/Query] to '[Relative Path/filename.csv]' csv header
example:
\COPY recipick_recipe TO 'recipes.csv' DELIMITER ',' CSV HEADER;
```
- [ ] ML back 완벽하게 짜기 + front랑 연결하기 ( 가격 고려해서 재배치(?))
- [x] create page에서 user-defined ingredients 추가하기 구현
- [x] edit page에서 recipe 삭제 기능
- [ ] 다양한 인풋을 handle할 수 있는지 보기
- [x] deploy 
- [ ] 데모때 뭐 할지 정하기
- [x] optimization
- [ ] Meal planner ml 추천 레시피 순서 저장 
- [ ] 버그 픽스
- [ ] load testing
- [ ] 개선할 부분 개선하기
  ...
